### PR TITLE
refactor: rename globalEvents to global_events

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

Renaming `globalEvents` to `global_events` to match other config options.

### CODE REVIEW

**Comment by bonustrack** [comment]
How do you define ABI for global events?

**Comment by Sekhmet** [comment]
@bonustrack it's not possible, I'm not sure if it should be possible - event names are generic so there might not be a single ABI for event named XYZ, so I imagine people working with those might want to handle those themselves, check if event is valid etc. but maybe it makes sense to still provide option to define ABI per event.

**Comment by bonustrack** [comment]
The events for ERC20 are standardized not only the functions, some contract may have more functions but the core ones like events name and types should always be the same, following this:  https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/token/erc20/library.cairo

**Comment by bonustrack** [comment]
Right, let's keep it without ABI for now. Do we return the event in `rawEvent`?

**Comment by Sekhmet** [comment]
Yes: https://github.com/snapshot-labs/checkpoint/blob/e61e967b5cf4590448c0b991cc364b0a87881477/src/providers/starknet/index.ts#L96

**Review by bonustrack — APPROVED** [review]
utACK

**Pull request merged**
